### ISSUE TITLE
Running Puppet Agent after restarting the puppetmaster service requires addition puppet agent runs

### ISSUE THREAD

**Issue by boconnell2210** [xebialabs/puppet-xldeploy#49] opened 2015-01-11 19:34 UTC
When I go to run the puppet agent, it takes 3 times to run the puppet agent to completion.  

Here are the 2 exceptions I get when running the agent, until the 3rd successful run:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/xldeploy_check_connection: Could not autoload puppet/provider/xldeploy_check_connection/port_check: no such file to load -- puppet_x/xebialabs/xldeploy/ci.rb on node dep-01.wdtablesystems.com
/usr/lib/ruby/site_ruby/1.8/puppet/indirector/rest.rb:207:in `is_http_200?'
/usr/lib/ruby/site_ruby/1.8/puppet/indirector/rest.rb:100:in `find'
/usr/lib/ruby/site_ruby/1.8/puppet/indirector/indirection.rb:201:in `find'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:256:in `retrieve_new_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:327:in `thinmark'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:326:in `thinmark'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:255:in `retrieve_new_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:60:in `retrieve_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:103:in `prepare_and_retrieve_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:170:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent/locker.rb:20:in `lock'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:117:in `with_client'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:44:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:82:in `run_in_fork'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:43:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `call'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `controlled_run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:41:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:355:in `onetime'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:321:in `run_command'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:477:in `plugin_hook'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:479:in `exit_on_fail'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:137:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:91:in `execute'
/usr/bin/puppet:8
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

==========================================================================================

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/xldeploy_ci: Could not autoload puppet/provider/xldeploy_ci/rest: no such file to load -- puppet_x/xebialabs/xldeploy/ci.rb on node dep-01.wdtablesystems.com
/usr/lib/ruby/site_ruby/1.8/puppet/indirector/rest.rb:207:in `is_http_200?'
/usr/lib/ruby/site_ruby/1.8/puppet/indirector/rest.rb:100:in `find'
/usr/lib/ruby/site_ruby/1.8/puppet/indirector/indirection.rb:201:in `find'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:256:in `retrieve_new_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:327:in `thinmark'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:326:in `thinmark'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:255:in `retrieve_new_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:60:in `retrieve_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:103:in `prepare_and_retrieve_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:170:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent/locker.rb:20:in `lock'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:117:in `with_client'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:44:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:82:in `run_in_fork'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:43:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `call'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `controlled_run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:41:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:355:in `onetime'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:321:in `run_command'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:477:in `plugin_hook'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:479:in `exit_on_fail'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:137:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:91:in `execute'
/usr/bin/puppet:8
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by WianVos** [comment] 2015-01-16 19:47
Hi Billy. 

i've been working on this for a while now .. but i have no clue on how to recreate this. 
What kind of setup are you running? 

p.s. Ivan says hi

**Comment by boconnell2210** [comment] 2015-01-19 15:33
Hey Wian,

Was away for the last few days.

I am using puppet/puppet-server version 3.7.3 on CentOS 6.5 operating system.  

Let me know any other information you think might be helpful.

Billy

**Comment by WianVos** [comment] 2015-01-19 15:41
?i'll get on it


________________________________

**Comment by WianVos** [comment] 2015-01-20 13:24
Billy .. question .. do u use puppet environments?

**Comment by boconnell2210** [comment] 2015-01-20 15:14
Wian,
I do not make use of puppet environments at this time.

**Comment by WianVos** [comment] 2015-03-06 12:29
been taking cracks at this for a while now .. can't reproduce .. 
Is this still a problem ?

**Comment by ltutar** [comment] 2015-03-06 21:53
I am able to  reproduce it. The first puppet agent run show the following message.

Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/root_home.rb
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/xldeploy_ci: Could not autoload puppet/provider/xldeploy_ci/rest: cannot load such file -- puppet_x/xebialabs/xldeploy/ci.rb on node agentcentos.localdomain
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
[root@agentcentos ~]# puppet agent -t

Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
[root@agentcentos ~]# puppet agent -t
Info: Retrieving plugin
Info: Loadi


The second run goes OK.

**Comment by boconnell2210** [comment] 2015-03-07 17:50
Yes, I still have the issue.

**Comment by ltutar** [comment] 2015-03-09 08:28
We are testing our theory. But I can write the following:
- Using puppet-enterprise-3.3.2-el-6-x86_64.tar as puppet master on centos
- Intalling the puppet agents through puppet node install on centos.
- Installed puppet module install xebialabs-xldeploy without dependencies.
Then I had the xldeploy_ci/rest issue with the first puppet agent -t 

- Installled xebialabs-xldeploy with the dependencies. The first puppet agent -t does lots of stuff with mcollective, like:
Notice: /Stage[main]/Pe_mcollective::Server::Plugins/File[/opt/puppet/libexec/mcollective/mcollective/agent/package.ddl]/ensure: defined content as '{md5}12f8dce7d996343068b9372f110279ed'
Notice: /Stage[main]/Pe_mcollective::Server::Plugins/File[/opt/puppet/libexec/mcollective/mcollective/agent/package.rb]/ensure: defined content as '{md5}51d279e034f236194a9bf45461cb6033'
Notice: /Stage[main]/Pe_mcollective::Server::Plugins/File[/opt/puppet/libexec/mcollective/mcollective/agent/puppet.ddl]/ensure: defined content as '{md5}e4de626b4ab250eab8bf33cfb303275d'
Notice: /Stage[main]/Pe_mcollective::Server::Plugins/File[/opt/puppet/libexec/mcollective/mcollective/agent/puppet.rb]/ensure: defined content as '{md5}d356b352d78f58ba48b66c4f56a86cf9'

No error, but the xldeploy module is still not called. After the second puppet run, the xldeploy module is called. Summary: No error this time but still a second run is needed to actually run the xldeploy module.
I'll keep posting when I know more. Maybe this helps the others to identify the problem.

**Comment by WianVos** [comment] 2015-03-13 13:07
i can reproduce this issue with puppet 3.7.2 .. not with 3.3.2 

boconnell2210: what puppet version are u on ?

**Comment by boconnell2210** [comment] 2015-03-13 15:12
I am using the following:

puppet --version
3.7.4

**Comment by zeke7237** [comment] 2015-04-20 13:44
So Billy dumped this problem on me :)

I've made numerous efforts to narrow the problem, with essentially no success. It appears to me that there's a chicken-egg situation where the deployit module is trying to initialize either before the supporting ruby stuff lands in /var/lib/puppet/lib or before puppet/ruby is aware of it (or configured to use it).

I've tried presetting RUBYLIB to include the paths in question, no joy there ..
> export RUBYLIB=/var/lib/puppet/lib/puppet_x/xebialabs/xldeploy:/var/lib/puppet/lib/puppet/type:/var/lib/puppet/lib/puppet/provider/xldeploy_check_connection

I sure could use another clue ..

**Comment by ltutar** [comment] 2015-11-09 11:59
I am also able to reproduce the problem with PE 2015.2 (puppet version 4.2.2)

[root@xldeployagent ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/xldeploy_check_connection: Could not autoload puppet/provider/xldeploy_check_connection/port_check: no such file to load -- puppet_x/xebialabs/xldeploy/ci at /etc/puppetlabs/code/environments/production/modules/xldeploy/manifests/server/post_config.pp:25:3 on node xldeployagent.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by ltutar** [comment] 2015-11-11 22:28
Following the advice of Sebastiaan (superseb) helped me. 
Move the xldeploy module from /etc/puppetlabs/code/environments/production/modules to /etc/puppetlabs/code/modules and restart the PE Master.
With the first puppet run, XL Deploy will be installed successfully with no errors.
Thanks Superseb.

**Closed** 2015-12-23 12:35 UTC
Labels: help wanted
